### ISSUE TITLE
[bug fix] sentiment analysis type error

### ISSUE THREAD

**Issue by kooyunmo** [swsnu/swpp2019-team20#138]
There is a TypeError while calculating the user rating score.

```
Internal Server Error: /review/1/
Traceback (most recent call last):
  File "/Users/Kooyunmo/Documents/swpp/swpp2019-team20/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/Kooyunmo/Documents/swpp/swpp2019-team20/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Kooyunmo/Documents/swpp/swpp2019-team20/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Kooyunmo/Documents/swpp/swpp2019-team20/backend/review/views.py", line 76, in user_review
    new_rating = (prev_rating * review_list_len + rating) / (review_list_len + 1)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int
```

**Comment by kooyunmo** [comment]
resolved with #137
